package cn.qtech.domain;

public class ManagerUserMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user_map.id
     *
     * @mbggenerated Mon Apr 17 15:50:22 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user_map.manager_id
     *
     * @mbggenerated Mon Apr 17 15:50:22 CST 2017
     */
    private String managerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user_map.user_id
     *
     * @mbggenerated Mon Apr 17 15:50:22 CST 2017
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user_map.id
     *
     * @return the value of manager_user_map.id
     *
     * @mbggenerated Mon Apr 17 15:50:22 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user_map.id
     *
     * @param id the value for manager_user_map.id
     *
     * @mbggenerated Mon Apr 17 15:50:22 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user_map.manager_id
     *
     * @return the value of manager_user_map.manager_id
     *
     * @mbggenerated Mon Apr 17 15:50:22 CST 2017
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user_map.manager_id
     *
     * @param managerId the value for manager_user_map.manager_id
     *
     * @mbggenerated Mon Apr 17 15:50:22 CST 2017
     */
    public void setManagerId(String managerId) {
        this.managerId = managerId == null ? null : managerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user_map.user_id
     *
     * @return the value of manager_user_map.user_id
     *
     * @mbggenerated Mon Apr 17 15:50:22 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user_map.user_id
     *
     * @param userId the value for manager_user_map.user_id
     *
     * @mbggenerated Mon Apr 17 15:50:22 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}