package cn.qtech.domain;

public class SubjectDifficulty {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject_difficulty.subject_id
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    private String subjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject_difficulty.type
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject_difficulty.name
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject_difficulty.description
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_difficulty.subject_id
     *
     * @return the value of subject_difficulty.subject_id
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    public String getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_difficulty.subject_id
     *
     * @param subjectId the value for subject_difficulty.subject_id
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId == null ? null : subjectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_difficulty.type
     *
     * @return the value of subject_difficulty.type
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_difficulty.type
     *
     * @param type the value for subject_difficulty.type
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_difficulty.name
     *
     * @return the value of subject_difficulty.name
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_difficulty.name
     *
     * @param name the value for subject_difficulty.name
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_difficulty.description
     *
     * @return the value of subject_difficulty.description
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_difficulty.description
     *
     * @param description the value for subject_difficulty.description
     *
     * @mbggenerated Tue Mar 21 14:20:39 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}