package cn.qtech.domain;

public class SubjectCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject_category.subject_category_id
     *
     * @mbggenerated Thu Mar 23 15:22:42 CST 2017
     */
    private String subjectCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject_category.type
     *
     * @mbggenerated Thu Mar 23 15:22:42 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject_category.name
     *
     * @mbggenerated Thu Mar 23 15:22:42 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject_category.description
     *
     * @mbggenerated Thu Mar 23 15:22:42 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_category.subject_category_id
     *
     * @return the value of subject_category.subject_category_id
     *
     * @mbggenerated Thu Mar 23 15:22:42 CST 2017
     */
    public String getSubjectCategoryId() {
        return subjectCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_category.subject_category_id
     *
     * @param subjectCategoryId the value for subject_category.subject_category_id
     *
     * @mbggenerated Thu Mar 23 15:22:42 CST 2017
     */
    public void setSubjectCategoryId(String subjectCategoryId) {
        this.subjectCategoryId = subjectCategoryId == null ? null : subjectCategoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_category.type
     *
     * @return the value of subject_category.type
     *
     * @mbggenerated Thu Mar 23 15:22:42 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_category.type
     *
     * @param type the value for subject_category.type
     *
     * @mbggenerated Thu Mar 23 15:22:42 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_category.name
     *
     * @return the value of subject_category.name
     *
     * @mbggenerated Thu Mar 23 15:22:42 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_category.name
     *
     * @param name the value for subject_category.name
     *
     * @mbggenerated Thu Mar 23 15:22:42 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject_category.description
     *
     * @return the value of subject_category.description
     *
     * @mbggenerated Thu Mar 23 15:22:42 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject_category.description
     *
     * @param description the value for subject_category.description
     *
     * @mbggenerated Thu Mar 23 15:22:42 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}