package cn.qtech.mapper;

import cn.qtech.domain.MakePaper;

public interface MakePaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table make_paper
     *
     * @mbggenerated Mon Apr 17 18:43:06 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table make_paper
     *
     * @mbggenerated Mon Apr 17 18:43:06 CST 2017
     */
    int insert(MakePaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table make_paper
     *
     * @mbggenerated Mon Apr 17 18:43:06 CST 2017
     */
    int insertSelective(MakePaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table make_paper
     *
     * @mbggenerated Mon Apr 17 18:43:06 CST 2017
     */
    MakePaper selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table make_paper
     *
     * @mbggenerated Mon Apr 17 18:43:06 CST 2017
     */
    int updateByPrimaryKeySelective(MakePaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table make_paper
     *
     * @mbggenerated Mon Apr 17 18:43:06 CST 2017
     */
    int updateByPrimaryKey(MakePaper record);
}