package cn.qtech.mapper;

import cn.qtech.domain.ManagerUserMap;

public interface ManagerUserMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user_map
     *
     * @mbggenerated Mon Apr 17 15:50:22 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user_map
     *
     * @mbggenerated Mon Apr 17 15:50:22 CST 2017
     */
    int insert(ManagerUserMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user_map
     *
     * @mbggenerated Mon Apr 17 15:50:22 CST 2017
     */
    int insertSelective(ManagerUserMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user_map
     *
     * @mbggenerated Mon Apr 17 15:50:22 CST 2017
     */
    ManagerUserMap selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user_map
     *
     * @mbggenerated Mon Apr 17 15:50:22 CST 2017
     */
    int updateByPrimaryKeySelective(ManagerUserMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_user_map
     *
     * @mbggenerated Mon Apr 17 15:50:22 CST 2017
     */
    int updateByPrimaryKey(ManagerUserMap record);
}