package cn.qtech.mapper;

import cn.qtech.domain.Paper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbggenerated Sun Apr 23 15:59:52 CST 2017
     */
    int deleteByPrimaryKey(String paperId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbggenerated Sun Apr 23 15:59:52 CST 2017
     */
    int insert(Paper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbggenerated Sun Apr 23 15:59:52 CST 2017
     */
    int insertSelective(Paper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbggenerated Sun Apr 23 15:59:52 CST 2017
     */
    Paper selectByPrimaryKey(String paperId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbggenerated Sun Apr 23 15:59:52 CST 2017
     */
    int updateByPrimaryKeySelective(Paper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbggenerated Sun Apr 23 15:59:52 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Paper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbggenerated Sun Apr 23 15:59:52 CST 2017
     */
    int updateByPrimaryKey(Paper record);

    List<Paper> queryAll();

    int addBaseinfo(Paper paper);


    int addContent(@Param("paperId") String paperId, @Param("content") String content);

    List<Paper> queryPapersByBatchPaperIds(@Param("paperIds") List<String> userPaperIds);
}