package cn.qtech.mapper;

import cn.qtech.domain.SubjectCategory;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SubjectCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_category
     *
     * @mbggenerated Thu Mar 23 15:22:42 CST 2017
     */
    int deleteByPrimaryKey(String subjectCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_category
     *
     * @mbggenerated Thu Mar 23 15:22:42 CST 2017
     */
    int insert(SubjectCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_category
     *
     * @mbggenerated Thu Mar 23 15:22:42 CST 2017
     */
    int insertSelective(SubjectCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_category
     *
     * @mbggenerated Thu Mar 23 15:22:42 CST 2017
     */
    SubjectCategory selectByPrimaryKey(String subjectCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_category
     *
     * @mbggenerated Thu Mar 23 15:22:42 CST 2017
     */
    int updateByPrimaryKeySelective(SubjectCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject_category
     *
     * @mbggenerated Thu Mar 23 15:22:42 CST 2017
     */
    int updateByPrimaryKey(SubjectCategory record);

    List<SubjectCategory> queryAll();

    boolean addSubjectCategory(SubjectCategory subjectCategory);

    List<SubjectCategory> queryCategoriesByBatchIds(@Param("ids") List<String> categoryIds);
}
