package cn.qtech.mapper;

import cn.qtech.domain.UserPaper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserPaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_paper
     *
     * @mbggenerated Mon Apr 17 15:59:32 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_paper
     *
     * @mbggenerated Mon Apr 17 15:59:32 CST 2017
     */
    int insert(UserPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_paper
     *
     * @mbggenerated Mon Apr 17 15:59:32 CST 2017
     */
    int insertSelective(UserPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_paper
     *
     * @mbggenerated Mon Apr 17 15:59:32 CST 2017
     */
    UserPaper selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_paper
     *
     * @mbggenerated Mon Apr 17 15:59:32 CST 2017
     */
    int updateByPrimaryKeySelective(UserPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_paper
     *
     * @mbggenerated Mon Apr 17 15:59:32 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(UserPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_paper
     *
     * @mbggenerated Mon Apr 17 15:59:32 CST 2017
     */
    int updateByPrimaryKey(UserPaper record);

    List<UserPaper> queryAllByUserIdAndStatus(@Param("userId") String userId, @Param("status") int status);

    boolean modifyContent(@Param("paperId") String paperId, @Param("content") String content);
}