package cn.qtech.domain;

import java.util.Date;

public class MakePaper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column make_paper.id
     *
     * @mbggenerated Mon Apr 17 18:43:06 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column make_paper.paper_id
     *
     * @mbggenerated Mon Apr 17 18:43:06 CST 2017
     */
    private String paperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column make_paper.user_id
     *
     * @mbggenerated Mon Apr 17 18:43:06 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column make_paper.create_time
     *
     * @mbggenerated Mon Apr 17 18:43:06 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column make_paper.total_time
     *
     * @mbggenerated Mon Apr 17 18:43:06 CST 2017
     */
    private Integer totalTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column make_paper.start_time
     *
     * @mbggenerated Mon Apr 17 18:43:06 CST 2017
     */
    private Date startTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column make_paper.id
     *
     * @return the value of make_paper.id
     *
     * @mbggenerated Mon Apr 17 18:43:06 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column make_paper.id
     *
     * @param id the value for make_paper.id
     *
     * @mbggenerated Mon Apr 17 18:43:06 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column make_paper.paper_id
     *
     * @return the value of make_paper.paper_id
     *
     * @mbggenerated Mon Apr 17 18:43:06 CST 2017
     */
    public String getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column make_paper.paper_id
     *
     * @param paperId the value for make_paper.paper_id
     *
     * @mbggenerated Mon Apr 17 18:43:06 CST 2017
     */
    public void setPaperId(String paperId) {
        this.paperId = paperId == null ? null : paperId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column make_paper.user_id
     *
     * @return the value of make_paper.user_id
     *
     * @mbggenerated Mon Apr 17 18:43:06 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column make_paper.user_id
     *
     * @param userId the value for make_paper.user_id
     *
     * @mbggenerated Mon Apr 17 18:43:06 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column make_paper.create_time
     *
     * @return the value of make_paper.create_time
     *
     * @mbggenerated Mon Apr 17 18:43:06 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column make_paper.create_time
     *
     * @param createTime the value for make_paper.create_time
     *
     * @mbggenerated Mon Apr 17 18:43:06 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column make_paper.total_time
     *
     * @return the value of make_paper.total_time
     *
     * @mbggenerated Mon Apr 17 18:43:06 CST 2017
     */
    public Integer getTotalTime() {
        return totalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column make_paper.total_time
     *
     * @param totalTime the value for make_paper.total_time
     *
     * @mbggenerated Mon Apr 17 18:43:06 CST 2017
     */
    public void setTotalTime(Integer totalTime) {
        this.totalTime = totalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column make_paper.start_time
     *
     * @return the value of make_paper.start_time
     *
     * @mbggenerated Mon Apr 17 18:43:06 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column make_paper.start_time
     *
     * @param startTime the value for make_paper.start_time
     *
     * @mbggenerated Mon Apr 17 18:43:06 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
}