package cn.qtech.domain;

public class UserPaper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_paper.id
     *
     * @mbggenerated Mon Apr 17 15:59:32 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_paper.user_id
     *
     * @mbggenerated Mon Apr 17 15:59:32 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_paper.status
     *
     * @mbggenerated Mon Apr 17 15:59:32 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_paper.content
     *
     * @mbggenerated Mon Apr 17 15:59:32 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_paper.id
     *
     * @return the value of user_paper.id
     *
     * @mbggenerated Mon Apr 17 15:59:32 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_paper.id
     *
     * @param id the value for user_paper.id
     *
     * @mbggenerated Mon Apr 17 15:59:32 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_paper.user_id
     *
     * @return the value of user_paper.user_id
     *
     * @mbggenerated Mon Apr 17 15:59:32 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_paper.user_id
     *
     * @param userId the value for user_paper.user_id
     *
     * @mbggenerated Mon Apr 17 15:59:32 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_paper.status
     *
     * @return the value of user_paper.status
     *
     * @mbggenerated Mon Apr 17 15:59:32 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_paper.status
     *
     * @param status the value for user_paper.status
     *
     * @mbggenerated Mon Apr 17 15:59:32 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_paper.content
     *
     * @return the value of user_paper.content
     *
     * @mbggenerated Mon Apr 17 15:59:32 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_paper.content
     *
     * @param content the value for user_paper.content
     *
     * @mbggenerated Mon Apr 17 15:59:32 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}