package cn.qtech.mapper;

import cn.qtech.domain.User;
import cn.qtech.domain.data.UserData;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Mar 14 18:06:39 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Mar 14 18:06:39 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Mar 14 18:06:39 CST 2017
     */
    int insertSelective(User record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Mar 14 18:06:39 CST 2017
     */
    User selectByPrimaryKey(String id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Mar 14 18:06:39 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Mar 14 18:06:39 CST 2017
     */
    int updateByPrimaryKey(User record);

    User queryByName(@Param("username") String username);

    List<User> queryUsersByBatchIds(@Param("ids") List<String> ids);

    int modifyPassword(@Param("name") String name, @Param("password") String password);

    List<UserData> queryUserNamesByBatchUserIds(@Param("userIds") List<String> userIds);
}
