package cn.qtech.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class Menu implements Serializable{
    private List<Menu> subMenus = new ArrayList<>();
    private int order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbggenerated Tue Mar 14 18:05:51 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.name
     *
     * @mbggenerated Tue Mar 14 18:05:51 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.icon
     *
     * @mbggenerated Tue Mar 14 18:05:51 CST 2017
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.router
     *
     * @mbggenerated Tue Mar 14 18:05:51 CST 2017
     */
    private String router;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.children
     *
     * @mbggenerated Tue Mar 14 18:05:51 CST 2017
     */
    private String children;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.parentId
     *
     * @mbggenerated Tue Mar 14 18:05:51 CST 2017
     */
    private String parentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.id
     *
     * @return the value of menu.id
     * @mbggenerated Tue Mar 14 18:05:51 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.id
     *
     * @param id the value for menu.id
     * @mbggenerated Tue Mar 14 18:05:51 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.name
     *
     * @return the value of menu.name
     * @mbggenerated Tue Mar 14 18:05:51 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.name
     *
     * @param name the value for menu.name
     * @mbggenerated Tue Mar 14 18:05:51 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.icon
     *
     * @return the value of menu.icon
     * @mbggenerated Tue Mar 14 18:05:51 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.icon
     *
     * @param icon the value for menu.icon
     * @mbggenerated Tue Mar 14 18:05:51 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.router
     *
     * @return the value of menu.router
     * @mbggenerated Tue Mar 14 18:05:51 CST 2017
     */
    public String getRouter() {
        return router;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.router
     *
     * @param router the value for menu.router
     * @mbggenerated Tue Mar 14 18:05:51 CST 2017
     */
    public void setRouter(String router) {
        this.router = router == null ? null : router.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.children
     *
     * @return the value of menu.children
     * @mbggenerated Tue Mar 14 18:05:51 CST 2017
     */
    public String getChildren() {
        return children;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.children
     *
     * @param children the value for menu.children
     * @mbggenerated Tue Mar 14 18:05:51 CST 2017
     */
    public void setChildren(String children) {
        this.children = children == null ? null : children.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.parentId
     *
     * @return the value of menu.parentId
     * @mbggenerated Tue Mar 14 18:05:51 CST 2017
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.parentId
     *
     * @param parentid the value for menu.parentId
     * @mbggenerated Tue Mar 14 18:05:51 CST 2017
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    public List<Menu> getSubMenus() {
        return subMenus;
    }

    public void setSubMenus(List<Menu> subMenus) {
        this.subMenus = subMenus;
    }

    public int getOrder() {
        return order;
    }

    public void setOrder(int order) {
        this.order = order;
    }
}
