package cn.qtech.domain;

public class UserRoleMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_map.id
     *
     * @mbggenerated Tue Mar 14 18:05:51 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_map.user_id
     *
     * @mbggenerated Tue Mar 14 18:05:51 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_map.role_id
     *
     * @mbggenerated Tue Mar 14 18:05:51 CST 2017
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_map.id
     *
     * @return the value of user_role_map.id
     *
     * @mbggenerated Tue Mar 14 18:05:51 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_map.id
     *
     * @param id the value for user_role_map.id
     *
     * @mbggenerated Tue Mar 14 18:05:51 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_map.user_id
     *
     * @return the value of user_role_map.user_id
     *
     * @mbggenerated Tue Mar 14 18:05:51 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_map.user_id
     *
     * @param userId the value for user_role_map.user_id
     *
     * @mbggenerated Tue Mar 14 18:05:51 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_map.role_id
     *
     * @return the value of user_role_map.role_id
     *
     * @mbggenerated Tue Mar 14 18:05:51 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_map.role_id
     *
     * @param roleId the value for user_role_map.role_id
     *
     * @mbggenerated Tue Mar 14 18:05:51 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}